-- creates everything the backend needs in supabase
-- run once in the supabase sql editor on a new project

create table if not exists danceclasses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  title text,
  instructor text,
  studio text,
  style text,
  -- times are stored in the studio's local time, without a time zone
  date timestamp without time zone,
  start_time timestamp without time zone,
  end_time timestamp without time zone,
  difficulty text,
  cancelled boolean,
  -- filled in by postgres, used by the time of day filter
  start_time_of_day time generated always as (start_time::time) stored,
  end_time_of_day time generated always as (end_time::time) stored
);

-- scrape_all clears the table before inserting fresh classes
-- data/danceclasses.py calls this with rpc('truncate_table', {'table_name': 'danceclasses'})
create or replace function truncate_table(table_name text)
returns void
language plpgsql
as $$
begin
  execute format('truncate table %I', table_name);
end;
$$;
